### ISSUE TITLE
It takes several seconds to response if userId doesn't exist

### ISSUE THREAD

**Issue by zcgandcomp** [wultra/user-data-store#113]
Call API
`GET /user-data-store/private/user-claims?userId=nonexistentId`

Expected behavior:
Proper error is returned at least in the same response time as for existing users.

Actual behavior:
It takes several seconds to return the error.

Trace:
(indicate there is some problem with error handling and closing of the request)
<img width="1574" alt="image" src="https://github.com/wultra/user-data-store/assets/10476400/e63b206f-2d91-43e2-8ee5-8e8c197ff1f9">

**Comment by banterCZ** [comment]
It seems that a very old version is deployed. Let's upgrade and retest.

**Comment by zcgandcomp** [comment]
After testing, this is probably affected by the used base image. The recommendation is to update to newer.

**Comment by banterCZ** [comment]
@zcgandcomp @korbelm Could you retest it please with JRE 21?

**Comment by korbelm** [comment]
v 1.2.0 with JRE21 works much better


![Image](https://github.com/wultra/user-data-store/assets/112644829/6a5d5e85-8752-40b2-b93f-78688db7edc0)
