### ISSUE TITLE
User Data Store (for Liveness)

### ISSUE THREAD

**Issue by zcgandcomp** [wultra/user-data-store#141]
As of now, all claims are in a single DB record.

For storing and retrieving data as requested in [Liveness Proxy](https://github.com/wultra/liveness-check-proxy/issues/13) we need to store a user photo as one claim and a timestamp when this photo was uploaded to iProove.

**Comment by romanstrobl** [comment]
Suggested DB structure:

```
CREATE SEQUENCE IF NOT EXISTS uds_user_claim_seq START WITH 1 INCREMENT BY 1 CACHE 20;

CREATE TABLE uds_user_claims_v2 (
   id INTEGER NOT NULL, 
   user_id VARCHAR(255) NOT NULL, 
   claim_name VARCHAR(255) NOT NULL, 
   claim_value TEXT, 
   encryption_mode VARCHAR(255) DEFAULT 'NO_ENCRYPTION' NOT NULL, 
   timestamp_created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), 
   timestamp_last_updated TIMESTAMP WITHOUT TIME ZONE, 
CONSTRAINT uds_user_claims_v2_pkey PRIMARY KEY (id));

CREATE INDEX uds_user_claim_user_idx ON uds_user_claims_v2(user_id);

CREATE UNIQUE INDEX uds_user_claim_name_idx ON uds_user_claims_v2(user_id, claim_name);
```

**Comment by romanstrobl** [comment]
I am closing the issue because the requirerement is invalid. Feel free to raise another issue once we analyze the requirements correctly.

**Comment by zcgandcomp** [comment]
DB Layer prepated (including migration)
Work on services and controllers.

**Comment by OliverJanstaWultra** [comment]
Expected to be ready by the end of this week.

**Comment by romanstrobl** [comment]
Pull request: https://github.com/wultra/user-data-store/pull/154

**Comment by romanstrobl** [comment]
I think we can merge this pull request.

I moved the remaining work into separate tickets:
https://github.com/wultra/user-data-store/issues/157
https://github.com/wultra/user-data-store/issues/158
