### ISSUE TITLE
Add support for OAuth2.0 authentication

### ISSUE THREAD

**Issue by zcgandcomp** [wultra/user-data-store#212]
Enable authentication as a resource server via Oauth2.0 JWT access tokens.

add to configuration (change accordingly):
- user-data-store.security.auth.type - enum OIDC / BASIC_HTTP
- user-data-store.security.auth.oidc.roles-claim - enable specification of claim containing roles
- spring.security.oauth2.resource-server.jwt.audiences - comma separated allowed audiences for UDS
- spring.security.oauth2.resource-server.jwt.issuer-uri - JWT issuer uri

**Comment by OliverJanstaWultra** [comment]
@korbelm please test this, if needed discuss with @banterCZ

**Comment by korbelm** [comment]
@banterCZ  how to enable OAUTH since there is no ENV VAR here: https://github.com/wultra/user-data-store/blob/1d72b16e66b6cd8abf557e2c2f3f053ca2eaaf70/user-data-store-server/src/main/resources/application.properties#L19 ??

**Comment by banterCZ** [comment]
> @banterCZ how to enable OAUTH since there is no ENV VAR here:
> 
> https://github.com/wultra/user-data-store/blob/1d72b16e66b6cd8abf557e2c2f3f053ca2eaaf70/user-data-store-server/src/main/resources/application.properties#L19
> 
> ??

@korbelm Yes, you are right, there is no ENV in the property file. But have you tried `USER_DATA_STORE_SECURITY_AUTH`? It's a standard Spring Boot binding mechanism, see https://stackoverflow.com/a/45822571/204950

**Comment by korbelm** [comment]
i did now as: USER_DATA_STORE_SECURITY_AUTH: OAUTH , but it is still basic auth

**Comment by korbelm** [comment]
works as expected
